// Subjects
export const GET_SUBJECTS = 'GET_PROJECTS'
export const GET_ACTUAL_SUBJECTS = 'GET_ACTUAL_PROJECTS'
export const ADD_SUBJECTS = 'ADD_PROJECT'
export const DELETE_SUBJECTS = 'DELETE_PROJECT'
export const HIDE_SUBJECTS = 'HIDE_PROJECTS'
// qualifications
export const QUALIFICATIONS_BY_SUBJECT = 'QUALIFICATIONS_BY_SUBJECT'
export const ADD_QUALIFICATION = 'ADD_QUALIFICATION'
export const DELETE_QUALIFICATION = 'DELETE_QUALIFICATION'
export const SET_STATE_QUALIFICATION = 'SET_STATE_QUALIFICATION'
export const SELECT_EDIT_QUALIFICATION = 'SELECT_EDIT_QUALIFICATION'
export const UPLOAD_QUALIFICATION = 'UPLOAD_QUALIFICATION'

// alerts
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

// auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const LOGOUT = 'LOGOUT'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_START = 'GET_USER_START'
export const GET_USER_ERROR = 'GET_USER_ERROR'
