// Subjects
export const GET_SUBJECTS_START = 'GET_SUBJECTS_START'
export const GET_SUBJECTS_SUCCESS = 'GET_SUBJECTS_SUCCESS'
export const GET_SUBJECTS_ERROR = 'GET_SUBJECTS_ERROR'
export const SELECT_SUBJECT = 'SELECT_SUBJECT'
export const ADD_SUBJECT_START = 'ADD_SUBJECT_START'
export const ADD_SUBJECT_SUCCESS = 'ADD_SUBJECT_SUCCESS'
export const DELETE_SUBJECT = 'DELETE_SUBJECT'
export const CLEAR_DATA_SUBJECT = 'CLEAR_DATA_SUBJECT'
// qualifications
// teacher
export const ADD_QUALIFICATION_START = 'ADD_QUALIFICATION_START'
export const ADD_QUALIFICATION_SUCCCESS = 'ADD_QUALIFICATION_SUCCESS'
export const QUALIFICATIONS_BY_STUDENT = 'QUALIFICATIONS_BY_STUDENT'
export const DELETE_QUALIFICATION = 'DELETE_QUALIFICATION'
export const SELECT_STUDENT = 'SELECT_STUDENT'
export const QUALIFICATION_ERROR = 'QUALIFICATION_ERROR'
// students
export const QUALIFICATIONS_BY_SUBJECT = 'QUALIFICATIONS_BY_SUBJECT'

// alerts
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

// auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const LOGOUT = 'LOGOUT'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_START = 'GET_USER_START'
export const GET_USER_ERROR = 'GET_USER_ERROR'
